version: "3.7"
services:
  # Envoy Proxy
  envoy:
    image: envoyproxy/envoy:v1.19.0
    # command: -c /etc/envoy/envoy.yaml -l trace
    command: -c /etc/envoy/envoy.yaml --component-log-level conn_handler:trace,connection:trace,client:trace
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./certs:/certs
    ports:
      - "80:9080"
      - "443:9443"
      - "9901:9901"
  
  # Backend HTTP
  products_http_service:
    image: kennethreitz/httpbin
    # ports:
      # - 8080:80

  external_process_service:
    image: docker.io/pubudu/ext-process-filter-envoy:v1
    # ports:
    #   - 18080:18080
